### ISSUE TITLE
defaults leaf qdisc should set hfsc

### ISSUE THREAD

**Issue by yutayu** [robinsmidsrod/SuperShaper-SOHO#1]
fq_codel + hfsc on Debian has known as issue.
then this script default leaf qdisc should set sfq
Thanks :)

**Comment by robinsmidsrod** [comment]
I'm actually using `LEAF_QDISC="sfq divisor 65536 headdrop"` on my local version these days, as I noticed `fq_codel noecn` wasn't behaving as well as I had hoped. This is on Ubuntu 14.04 with kernel 4.4.0-134-generic.

Do you have a link to the information that says _why_ Debian has an issue with fq_codel and hfsc?

**Comment by yutayu** [comment]
Hi , great jobs :)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901660

https://bugs.openwrt.org/index.php?do=details&task_id=1136
https://bugs.centos.org/view.php?id=14413

**Comment by yutayu** [comment]
Mine is
    $TC qdisc add dev $DEV root handle 1: stab linklayer atm overhead -4 hfsc default 50
LEAF_QDISC="sfq perturb 10 quantum 1590"

1590 is multipul of 53.

**Comment by yutayu** [comment]
I am sorry not to tell you that is under raspbian.
this seems special kernel .
Excuse me. don't mind.
